// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfjkmikwucewykvjfkit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmamttaWt3dWNld3lrdmpma2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzODgxNjcsImV4cCI6MjA1Mzk2NDE2N30.buqS5-QaNvQFczNJmmvU8JknMXE0T7j7G_eCjEnK1j8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);